// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Tasha-kyb/my-telegram-bot/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type ExpenseRepository struct {
	mock.Mock
}

// AddExpense provides a mock function with given fields: ctx, expense
func (_m *ExpenseRepository) AddExpense(ctx context.Context, expense *model.Expense) (*model.Expense, error) {
	ret := _m.Called(ctx, expense)

	if len(ret) == 0 {
		panic("no return value specified for AddExpense")
	}

	var r0 *model.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Expense) (*model.Expense, error)); ok {
		return rf(ctx, expense)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Expense) *model.Expense); ok {
		r0 = rf(ctx, expense)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Expense) error); ok {
		r1 = rf(ctx, expense)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MonthExpense provides a mock function with given fields: ctx, userID
func (_m *ExpenseRepository) MonthExpense(ctx context.Context, userID int64) ([]model.Expense, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MonthExpense")
	}

	var r0 []model.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Expense, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Expense); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatsExpense provides a mock function with given fields: ctx, userID
func (_m *ExpenseRepository) StatsExpense(ctx context.Context, userID int64) ([]model.Expense, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for StatsExpense")
	}

	var r0 []model.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Expense, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Expense); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TodayExpense provides a mock function with given fields: ctx, userID
func (_m *ExpenseRepository) TodayExpense(ctx context.Context, userID int64) ([]model.Expense, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for TodayExpense")
	}

	var r0 []model.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Expense, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Expense); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WeekExpense provides a mock function with given fields: ctx, userID
func (_m *ExpenseRepository) WeekExpense(ctx context.Context, userID int64) ([]model.Expense, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for WeekExpense")
	}

	var r0 []model.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Expense, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Expense); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExpenseRepository creates a new instance of ExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseRepository {
	mock := &ExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
